name: alumni_network
description: "Alumni Network Platform Mobile and Web client."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages:
  intl: 0.17.0
  flutter_bloc: 8.1.3
  flutter_secure_storage: 9.0.0
  google_sign_in: 6.2.1
  equatable: 2.0.5
  get_it: 7.6.4
  dio: 5.3.3

  # UI packages:
  cached_network_image: 3.3.0
  pdf_render: 1.4.8

  # Firebase:
  firebase_core: 2.25.4
  firebase_messaging: 14.7.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
