# Generated by Django 4.2.1 on 2023-12-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniStudentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('study_start_year', models.IntegerField()),
                ('student_number', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='alumniuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumniuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
