# Generated by Django 4.2.1 on 2023-12-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alumnistudentdraft_alter_alumniuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnistudentdraft',
            name='student_number',
        ),
        migrations.RemoveField(
            model_name='alumnistudentdraft',
            name='study_start_year',
        ),
    ]
