# Generated by Django 4.2.1 on 2023-12-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_alumnistudentdraft_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnistudentdraft',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
