# Generated by Django 4.2.1 on 2023-12-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_alumnistudentdraft_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnistudentdraft',
            name='image_path',
        ),
        migrations.AddField(
            model_name='alumnistudentdraft',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
