# Generated by Django 4.2.1 on 2023-12-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_alumnistudentdraft_image_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniStudentDraft',
        ),
        migrations.AddField(
            model_name='academicdegree',
            name='level_name',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
