# Generated by Django 4.2.1 on 2023-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_alumnistudentdraft_academicdegree_level_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdefense',
            name='commission_member_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='thesisdefense',
            name='commission_member_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='thesisdefense',
            name='commission_member_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
