# Generated by Django 4.2.1 on 2023-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_thesisdefense_commission_member_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
