# Generated by Django 4.2.1 on 2024-02-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_alumniuser_user_alter_studentuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('examination_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.examinationperiod')),
            ],
        ),
    ]
