# Generated by Django 4.2.1 on 2024-02-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_examinationperiod_examinationentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationperiod',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
