version: "3.9"
   
services:

  alumninet:
    build:
      dockerfile: Dockerfile
      context: ./alumninet
    container_name: alumninet
    command: sh -c "python manage.py runserver --nostatic 0.0.0.0:80"
    env_file: 
      - ./env
    ports:
      - '8080:80'
    restart: unless-stopped
    volumes:
      - ./alumninet:/usr/src/app
      - ./db:/usr/src/app/db
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '4000:9090'
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, grafana-simple-json-datasource"
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

  exporter:
    image: prom/node-exporter
    container_name: node
    ports:
    - '9100:9100'
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    command:
    - '--path.procfs=/host/proc'
    - '--path.rootfs=/rootfs'
    - '--path.sysfs=/host/sys'
    - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    depends_on:
    - prometheus 