global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api
    metrics_path: '/prometheus-xyzabc/metrics'
    static_configs:
      - targets: ['alumninet']
  - job_name: node-exporter
    static_configs:
      - targets: ['node:9100']
